name: Build web app and deploy to Firebase Hosting

on:
  pull_request_target:
    types: [closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'release-please--branches--master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run release job
        run: cd web && npm ci && npm run build && cd ../firebase

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KORPORAOUEG }}'
          channelId: live
          projectId: korporaoueg