name: Create a release PR and deploy to Firebase Hosting

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.commits[0].author.name != 'github-actions[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd web && npm ci

      - name: Run unit tests
        run: cd web && npx vitest run

  release-please:
    runs-on: ubuntu-latest
    needs: test
    if:  github.event.commits[0].author.name != 'github-actions[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build_and_deploy:
    runs-on: ubuntu-latest
    if:  github.event.commits[0].author.name == 'github-actions[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run release job
        run: cd web && npm ci && npm run build && cd ../firebase

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: firebase
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KORPORAOUEG }}'
          channelId: live
          projectId: korporaoueg
