name: Release Please

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release-please--branches--master')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
  deploy:
    runs-on: ubuntu-latest
    needs: release-please
    if: contains(github.event.head_commit.message, 'release-please--branches--master')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run release job
        run: cd web && npm ci && npm run build && cd ../firebase

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: korporaoueg